version: '3.7'
services:

  smartvuefront:
    build:
      context: ../Smart Vue Frontend
      dockerfile: Dockerfile
      args:        
        GENERATOR_ENDPOINT: https://gwapim.dfil-tech.eu/scg/
        PROXY_ENDPOINT: https://gwapim.dfil-tech.eu/scp/
        # GENERATOR_ENDPOINT: http://localhost:8080/smartweb/
        # PROXY_ENDPOINT: http://localhost:8082/smartproxy/
    ports:
      - 4000:80    
