version: '3.7'
services:

  vuefront:
    build:
      context: .
      dockerfile: Dockerfile
      args:        
        GENERATOR_ENDPOINT: https://www.example1.com
        PROXY_ENDPOINT: https://www.example2.com
    ports:
      - 4000:80    
